name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  intl: ^0.19.0
  uuid: ^4.4.2

  user_repository:
    path: packages/user_repository
    
  contact_repository:
    path: packages/contact_repository
    
  chat_repository:
    path: packages/chat_repository


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
