name: contact_repository
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  path: ^1.9.0
  rxdart: ^0.28.0
  firebase_storage: ^12.1.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
